### ISSUE TITLE
[desktop/Chrome] Team: main navigation to show active page

### ISSUE THREAD

**Issue by jennifer-cuberis** [cuberis/REDD#31]
On all internal pages the navigation should indicate the active page as dark, with the other as medium grey 898989. (I see that that grey isn't in the style guide, sorry, but the light is too light to be legible in this type.)

![screen shot 2015-02-02 at 2 31 11 pm](https://cloud.githubusercontent.com/assets/10439344/6007866/669dd28e-aaeb-11e4-9336-f2cf31f5587f.png)

**Comment by ethanbutler** [comment]
resolved + pushed
