### ISSUE TITLE
[desktop/Chrome] Studies: dropdown nav needs more padding

### ISSUE THREAD

**Issue by jennifer-cuberis** [cuberis/REDD#33]
requesting more padding above and below the content. The box was also specked a bit lighter, but let me know your thoughts.

![screen shot 2015-02-02 at 2 54 09 pm](https://cloud.githubusercontent.com/assets/10439344/6008192/acbdb39a-aaed-11e4-8eda-269b70bd1202.png)
![screen shot 2015-02-02 at 2 53 18 pm](https://cloud.githubusercontent.com/assets/10439344/6008193/ae983d5c-aaed-11e4-9566-43035dd6945c.png)

**Comment by ethanbutler** [comment]
resolved!
